<?php
/**
 * Created by PhpStorm.
 * User: rafael
 * Date: 11/4/18
 * Time: 17:37
 */
require_once ("UserNoR.php");
class UserR extends UserNoR
{
    protected $idUser;
    protected $name;
    protected $nick;
    protected $password;
    protected $status;
    protected $email;
    //protected $followers;
    //protected $followings;
    //protected Tuins $numtuins;
    public $message;

    public function construct()
    {
        $this->db_name;
    }

    public function get($idUser = "")
    {

        if ($idUser != "") {
            $this->query = "SELECT * FROM userr WHERE idUser ='$idUser'";
            $this->get_results_from_query();
        }
        if (count($this->rows) == 1) {
            foreach ($this->rows[0] as $campo => $valor) {
                $this->$campo = $valor;
            }
            $this->menssage = "Se encontró el usuario";
        } else {
            $this->menssage = "No se encontró el usuario";
        }
    }

    public function getIdUser()
    {
        return $this->idUser;
    }

    public function getName()
    {
        return $this->name;
    }

    public function getNick()
    {
        return $this->nick;
    }

    public function getStatus()
    {
        return $this->status;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function set($user_data = array())
    {
        parent::set(); // TODO: Change the autogenerated stub
        foreach ($user_data as $campo => $valor) {
            $this->$campo = $valor;
        }
        $this->query = "SELECT * FROM userr WHERE idUser ='$this->email'";
        $this->get_results_from_query();
        if (count($this->rows) == 1) {
            $this->mensaje = "Usuario existente";
        } else {
            unset($this->rows);
            $this->query = "INSERT INTO userr (nick, pass, repass, email, telefono) VALUES ('$this->nick', '$this->password', '', '$this->email', '$this->telefono')";
            $this->execute_single_query();
            $this->message = "usuario creado";
        }
    }

    public function setCampos($user_data = array()){
        if (array_key_exists('idUser', $user_data)) {
            foreach ($user_data as $campo => $valor) {
                $this->$campo = $valor;
            }
            //$this->query ="UPDATE userr SET nick =$this->nick,pass =$this->password,email=$this->email,telefono = $this->email WHERE idUser=$this->idUser";
            $this->query = "UPDATE `userr` SET `nick` = '$this->nick', `pass` = '$this->password', `repass` = 'juan4', `email` = '$this->email', `telefono` = '$this->email' WHERE `userr`.`idUser` = $this->idUser;";
            $this->execute_single_query();
            $this->message = "Se actulizo el usuario";
        } else {
            $this->message = "Error";
        }
    }
    public function settName()
    {
        return $this->name;
    }

    public function settNick()
    {
        return $this->nick;
    }

    public function settStatus()
    {
        return $this->status;
    }

    public function del($idUser = ''){
        parent::del(); // TODO: Change the autogenerated stub
        if ($idUser != '') {
            $this->query = "DELETE FROM userr WHERE idUser='$idUser'";
            $this->execute_single_query();
            $this->message ="Se elimino el usuario";
        }
        else{
            $this->message="Error";
        }
    }
    public function init_Session($nick ='' ,$password=''){
        if(empty($nick) || empty($password)){
            $this->message= 'Ha dejado algun recuadro en blanco. Intentelo de nuevo.';
        }

        $this->query = "SELECT * FROM userr WHERE nick = '$nick'  AND pass='$password'";
        $this->get_results_from_query();
        $tipo = "usuario";
        if(count($this->rows) == 1){
            foreach ($this->rows[0] as $campo =>$valor){
                $this->$campo =$valor;
            }
            session_start();
            $_SESSION['usuario'] = $this->nick;
            $_SESSION['login'] = true;
            $_SESSION['tipo'] = $tipo;
            $_SESSION['idUser'] = $this->idUser;
            $this->message ="Sesión iniciada";
        }
        else{
            $this->message = "Error al iniciar sesion. Intentelo de nuevo.";
            //$tipo = "ninguno"; //No se si esto es necesario
        }
    }
}